
- name: Ruby on Rails 7.0
  excerpt: "Ruby on Rails 7.0 Training"
  url: /trainings/rails.html
  duration: 2
  trainings:
    - date: 2023-01-23
      location: Koblenz
  price: 1750
  tags:
    - Rails

- name: Phoenix Framework
  excerpt: "Phoenix Anfänger Training"
  url: /trainings/phoenix.html
  duration: 2
  trainings:
    - date: 2023-01-30
      location: Koblenz
  price: 1750
  tags:
    - Phoenix

- name: WebPerformance
  excerpt: "Fussgängerzone oder Autobahn?"
  url: /trainings/webperformance.html
  duration: 1
  trainings:
    - date: 2023-02-07
      location: Koblenz
  price: 1900
  tags:
    - WebPerf
